#!/bin/bash

#this is a bash script that will look at the all the files in my downloads folder
# Defining the folder where the files to be sorted are located
input_folder="/Users/{username}/Downloads"

# Loop through the files in the input folder
for file in "$input_folder"/*; do
    if [[ "$file" == *.png ]] | [[ "$file" == *.jpg ]]; then
        mv "$file" /Users/{username}/Pictures
        echo "Picture Moved - $file"
    elif [[ "$file" == *.mov ]] | [[ "$file" == *.mp4 ]]; then
          mv "$file" /Users/{username}/Movies
          echo "Movies Moved - $file"
    else
        echo "Not Moved - $file"
  fi
done
